/* eslint-disable no-unused-vars */
export enum CategoryType {
    UNIT = 'UNIT',
    PURPOSE = 'PURPOSE',
    PACKAGE_UNIT = 'PACKAGE_UNIT',
    WEIGHT_UNIT = 'WEIGHT_UNIT',
    DENSITY_UNIT = 'DENSITY_UNIT',
    AREA_UNIT = 'AREA_UNIT',
    LENGTH_UNIT = 'LENGTH_UNIT',
    MATERIAL = 'MATERIAL',
    RESOURCE = 'RESOURCE',
    CHICKEN = 'CHICKEN',
    TASK_TYPE = 'TASK_TYPE',
    TIME_UNIT = 'TIME_UNIT',
    QUANTITY_UNIT = 'QUANTITY_UNIT',
}
