/* eslint-disable no-unused-vars */
export enum NotificationTypeEnum {
    // TASK = 'TASK',
    // ASSIGNMENT = 'ASSIGNMENT',
    // BREEDING_AREA = 'BREEDING_AREA',
    // FARM = 'FARM',
    // INVENTORY_REQUEST = 'INVENTORY_REQUEST',
    // INVENTORY_RECEIPT = 'INVENTORY_RECEIPT',
    // WAREHOUSE = 'WAREHOUSE',
    // WAREHOUSE_STOCK = 'WAREHOUSE_STOCK',
    // HARVEST_PRODUCT = 'HARVEST_PRODUCT',
    // HARVEST_PRODUCT_RECEIPT = 'HARVEST_PRODUCT_RECEIPT',
    INVITE_FARM = 'INVITE_FARM',
    ENROLL_FARM = 'ENROLL_FARM',
}
