const routes = {
    home: '/',
    signIn: '/sign-in',
    signUp: '/sign-up',
    dashboard: '/dashboard',
    welcome: '/welcome',
    farm: '/farm',
    farmRegister: '/farm/register',
    breadingArea: '/breeding-area',
    chickenCoop: '/chicken-coop',
    equipment: '/equipment',
    flock: '/flock',
    request: '/request',
    createRequest: '/request/create',
    food: '/warehouse/foods',
    category: '/category',
    categoryAll: '/category/all',
    categoryUnit: '/category/unit',
    employee: '/employee',
    farmEmployee: '/farm-employee',
    inventoryReceipt: '/warehouse/inventory-receipt',
    // createReceipt: 'inventory-receipt/create',
    profile: '/profile',
    chickenBatch: '/chicken-batch',
    nutritionPlan: '/nutrition-plan',
    createNutritionPlan: '/nutrition-plan/create',
    updateNutritionPlan: '/nutrition-plan/update',
    forgotPassword: '/forgot-password',
    inputOTP: 'forgot-password/input-OTP',
    resetPassword: '/reset-password',
    growthStage: '/growth-stage',
    chicken: '/chicken',
    breeding: '/warehouse/breeding',
    harvest: '/warehouse/harvest',
    task: '/task',
    createTask: '/task/create',
    assignment: '/assignment',
    shift: '/shift',
    settings: '/settings',
    supplier: '/supplier',
    resourceSupplier: 'supplier/resource-supplier',
    ware: '/warehouse',
    medicine: '/warehouse/medicines',
    config: '/config',
    commonWarehouse: '/warehouse/common',
    stockReceipt: '/stock-receipt',
    createStockReceipt: '/stock-receipt/create'
};

export default routes;
