const routes = {
    home: '/',
    signIn: '/sign-in',
    signUp: '/sign-up',
    dashboard: '/dashboard',
    farm: '/farm',
    farmRegister: '/farm/register',
    breadingArea: '/breeding-area',
    chickenCoop: '/chicken-coop',
    equipment: '/equipment',
    flock: '/flock',
    request: '/request',
    createRequest: '/request/create',
    food: '/warehouse/foods',
    category: '/category',
    categoryAll: '/category/all',
    categoryUnit: '/category/unit',
    vaccine: '/warehouse/vaccines',
    employee: '/employee',
    farmEmployee: '/farm-employee',
    inventoryReceipt: '/warehouse/inventory-receipt',
    createReceipt: 'inventory-receipt/create',
    profile: '/profile',
    chickenBatch: '/chicken-batch',
    nutritionPlan: '/nutrition-plan',
    forgotPassword: '/forgot-password',
    inputOTP: 'forgot-password/input-OTP',
    resetPassword: '/reset-password',
    growthStage: '/growth-stage',
    chicken: '/chicken',
    task: '/task',
    createTask: '/task/create',
    updateTask: '/task/edit',
};

export default routes;
