name: Build Docker image

on:
    pull_request:
        branches:
            - main
            - dev

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build Docker image
              run: docker build -t nextjs-app .

            - name: Verify Docker image
              run: docker images
